#!/root/kubernetes/ansible/myansible/bin/ansible-playbook

- name: This is Overview of Ansible Debug Module
  hosts: all
  remote_user: ec2-user
  become: 'yes'
  become_user: root

  vars:
    test: hello, this is dummy value
    my_name: Dorian Shurdhi
    my_age: 31
    is_male: yes

  tasks:
    - name: Reading Ansible Playbook Variable through var
      debug:
        var: test

    - name: Reading Ansible Playbook Variable through msg
      debug:
        msg: 
           - My name is {{ my_name }}
           - I'm {{ my_age }} years old
           - my gender is male - {{ is_male }}.

