#!/root/kubernetes/ansible/myansible/bin/ansible-playbook

- name: This is Overview of Ansible ans Set_Fact
  hosts: all
  remote_user: ec2-user
  become: 'yes'
  become_user: root

  tasks:
    - name: Retrieve Installed Shell Version
      shell: "bash --version"
      register: bash_ver

    - set_fact:
       #in this way we can filter our desidered output
        bash_version: "{{bash_ver.stdout_lines[0].split()[3].split('(')[0]}}"

    - debug:
        var: bash_version
