#!/root/kubernetes/ansible/myansible/bin/ansible-playbook

- name: This will show the Use of Comparision Operators
  hosts: localhost
  gather_facts: false

  vars:
    a : "HELLO"
    d : "hello"
    b : 10
    c : 20
    e : [1,5,9,10,15,109]
    x: "/root/ansible/operators_statement"
    y: "/root/ansible/operators_statement/comparision_operator.yml"

  tasks:
    - name: Operations on variables
      debug:
        msg:
          - "The List is - {{ e }}, Value of c is - {{ c }} and Value of b is - {{ b }}"
          - "Is b memeber of e : {{ b in e }}"
          - "Is c memeber of e : {{ c in e }}"
          - "Is 25 memeber of e : {{ 25 in e }}"
          - "Is c not a memeber of e : {{ c not in e }}"
