#!/root/kubernetes/ansible/myansible/bin/ansible-playbook

- name: Introduction Ansible Playbook
  hosts: all
  remote_user: ec2-user
  become: 'yes'
  become_user: root
 
  tasks:
  - name: Checking conncetion via ping
    ping:
  
  - name: Uninstall Apache
    yum:
      name: httpd
      state: absent

